### PR TITLE
Fix

### PR DESCRIPTION
**Pull request by Henry2o1o**

### CODE REVIEW

**Comment by gwolf2u** [comment]
please use Crowdin for translations 
https://crdroid.net/translations.php

**Comment by Henry2o1o** [comment]
> please use Crowdin for translations
> https://crdroid.net/translations.php

I have adjusted/changed a lot in Crowdin.

**Comment by gwolf2u** [comment]
I've added you as proofreader in Crowdin so you can approve german translations and fix wrong ones

**Comment by Henry2o1o** [comment]
> I've added you as proofreader in Crowdin so you can approve german translations and fix wrong ones

ok 👍

**Comment by Henry2o1o** [comment]
Sie, Ihr or Du, Deine?
Personal Pronouns

**Comment by gwolf2u** [comment]
not up to me
german not my native language

**Comment by Henry2o1o** [comment]
Page 1- 10 revised, more to follow...

**Pull request closed without merging**
