### PR TITLE
Small changes/adjustments

### PR DESCRIPTION
**Pull request by Henry2o1o**
I had already inserted them at Crowdin, but they were not taken over yet. 

either all applications or apps...
either all icons or symbols...
and, and, and...

### CODE REVIEW

**Comment by gwolf2u** [comment]
added to Crowdin 
will get merged on next translation review cycle

**Comment by Henry2o1o** [comment]
https://crowdin.com/translate/crdroid-translation/all/en-de#q=dash

`But users in Europe will soon have to say goodbye to Dash Charge too. Not because the feature will be removed in the future, but because the name disappears for trademark reasons. The name does not appear in the presentation of the smartphone, nor on the OnePlus or Amazon website. Here we are only talking about "Fast Charging". The reason for the renaming is an application submitted by OnePlus in 2016 to register the trademark with the EUIPO (European Union Intellectual Property Office), which was however rejected in April of this year. According to the rejection notice, there were two appeals. For example, the audio headset manufacturer Bragi has a similarly named product with "The Dash", and Amazon sees a risk of confusion with its own dash buttons. Although the manufacturer may continue to use the name, it decided to rename it due to the lack of registration as a trademark.`

**### What do we call this now?**

Quick Charge - Schnellladen, Schnelles Laden, Schnelles Aufladen?

**Comment by gwolf2u** [comment]
Just name it Warp charge 😉

**Comment by Henry2o1o** [comment]
> Just name it Warp charge 😉

in German also 😂

**Comment by Henry2o1o** [comment]
> added to Crowdin
> will get merged on next translation review cycle

When does this take place?

**Comment by gwolf2u** [comment]
https://github.com/crdroidandroid/android_packages_apps_crDroidSettings/pull/529
When this is merged
No timeframe 
Usually when enough translations are ready

**Pull request closed without merging**
