### PR TITLE
Update Italian translations

### PR DESCRIPTION
**Pull request by entony80**

### CODE REVIEW

**Comment by entony80** [comment]
What is the problem of translations?

**Comment by neobuddy89** [comment]
@hokiealumnus Can you test this commit locally first? See if it compiles good?

@entony80 I am on vacation - need to test commit for compilation error before merge.

**Comment by entony80** [comment]
I'm not able to compile, whenever possible you control yourself,  i translated from the original.
Good holidays

**Comment by firebird11** [comment]
still error on line 1509

**Comment by entony80** [comment]
line 1509 is < /resources > I do not understand how it goes in error.

**Comment by firebird11** [comment]
try to build it and see yourself, fix it and make new pull request

**Pull request closed without merging**
