### PR TITLE
ConfigCenter: Introduce Adaptive Playback [2/2]

### PR DESCRIPTION
**Pull request by uixdess**

### CODE REVIEW

**Comment by sysxda** [comment]
<com.havoc.support.preferences. ? Use <com.crdroid.settings.preferences.

**Comment by uixdess** [comment]
whoops, when started to push my local changes were overriden

**Comment by sysxda** [comment]
Also maybe better move this to sound settings ? @neobuddy89 , @gwolf2u

**Comment by gwolf2u** [comment]
moved to WIP branch
https://github.com/crdroidandroid/android_packages_apps_crDroidSettings/commit/dde25fbbcee43e5ce916608ba89acd439c4a9446

**Pull request closed without merging**
