### PR TITLE
Create crdroid_strings.xml

### PR DESCRIPTION
**Pull request by Henry2o1o**

### CODE REVIEW

**Review by neobuddy89 — CHANGES_REQUESTED** [review]
Seems incomplete.

**Comment by Henry2o1o** [comment]
I am still here...

I just see there are 2 brunches.
I'm in the wrong brunch.

What about crowdin, i would like to translate it there.

This is much faster.

crowdin profile:
Henry2o1o

**Comment by Henry2o1o** [comment]
github desktop for windows

unbenannt1

unbenannt

**Comment by Henry2o1o** [comment]
I can't get to it right now, excuse me.

**Pull request closed without merging**
